GLOBAL move:PROC
GLOBAL boost:PROC
GLOBAL slow:PROC

GLOBAL check_collisions:PROC

GLOBAL __winning_player:DWORD

GLOBAL __first_plane_x:DWORD
GLOBAL __first_plane_y:DWORD
GLOBAL __second_plane_x:DWORD
GLOBAL __second_plane_y:DWORD

GLOBAL powerupflag:BYTE
GLOBAL powerupflag2:BYTE

GLOBAL powerup_x:DWORD
GLOBAL powerup_y:DWORD
GLOBAL finishline_y:DWORD


GLOBAL slowerflag:BYTE
GLOBAL slowerflag2:BYTE

GLOBAL slower_x:DWORD
GLOBAL slower_y:DWORD
